//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softball.Mvc4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int GameID { get; set; }
        public string GameLocation { get; set; }
        public Nullable<System.DateTime> GameDate { get; set; }
        public bool AtHomeFirst { get; set; }
        public string GameStatus { get; set; }
        public string Game1Result { get; set; }
        public string Game2Result { get; set; }
        public string Opponent { get; set; }
    }
}
