//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softball.Mvc4
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleDetailView
    {
        public int ScheduleID { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        public string Location { get; set; }
        public string HomeTeam { get; set; }
        public string HomeManager { get; set; }
        public string AwayTeam { get; set; }
        public string AwayManager { get; set; }
    }
}
