//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SoftballModel", "FK_Schedule_Team", "Team", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Softball.Mvc4.Team), "Schedule", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Softball.Mvc4.Schedule), true)]
[assembly: EdmRelationshipAttribute("SoftballModel", "FK_Schedule_Team1", "Team", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Softball.Mvc4.Team), "Schedule", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Softball.Mvc4.Schedule), true)]

#endregion

namespace Softball.Mvc4
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SoftballEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SoftballEntities object using the connection string found in the 'SoftballEntities' section of the application configuration file.
        /// </summary>
        public SoftballEntities() : base("name=SoftballEntities", "SoftballEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SoftballEntities object.
        /// </summary>
        public SoftballEntities(string connectionString) : base(connectionString, "SoftballEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SoftballEntities object.
        /// </summary>
        public SoftballEntities(EntityConnection connection) : base(connection, "SoftballEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Game> Games
        {
            get
            {
                if ((_Games == null))
                {
                    _Games = base.CreateObjectSet<Game>("Games");
                }
                return _Games;
            }
        }
        private ObjectSet<Game> _Games;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Player> Players
        {
            get
            {
                if ((_Players == null))
                {
                    _Players = base.CreateObjectSet<Player>("Players");
                }
                return _Players;
            }
        }
        private ObjectSet<Player> _Players;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Schedule> Schedules
        {
            get
            {
                if ((_Schedules == null))
                {
                    _Schedules = base.CreateObjectSet<Schedule>("Schedules");
                }
                return _Schedules;
            }
        }
        private ObjectSet<Schedule> _Schedules;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Team> Teams
        {
            get
            {
                if ((_Teams == null))
                {
                    _Teams = base.CreateObjectSet<Team>("Teams");
                }
                return _Teams;
            }
        }
        private ObjectSet<Team> _Teams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ScheduleDetailView> ScheduleDetailViews
        {
            get
            {
                if ((_ScheduleDetailViews == null))
                {
                    _ScheduleDetailViews = base.CreateObjectSet<ScheduleDetailView>("ScheduleDetailViews");
                }
                return _ScheduleDetailViews;
            }
        }
        private ObjectSet<ScheduleDetailView> _ScheduleDetailViews;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<WonLostDetailView> WonLostDetailViews
        {
            get
            {
                if ((_WonLostDetailViews == null))
                {
                    _WonLostDetailViews = base.CreateObjectSet<WonLostDetailView>("WonLostDetailViews");
                }
                return _WonLostDetailViews;
            }
        }
        private ObjectSet<WonLostDetailView> _WonLostDetailViews;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Games EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGames(Game game)
        {
            base.AddObject("Games", game);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Players EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPlayers(Player player)
        {
            base.AddObject("Players", player);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Schedules EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSchedules(Schedule schedule)
        {
            base.AddObject("Schedules", schedule);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Teams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTeams(Team team)
        {
            base.AddObject("Teams", team);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ScheduleDetailViews EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToScheduleDetailViews(ScheduleDetailView scheduleDetailView)
        {
            base.AddObject("ScheduleDetailViews", scheduleDetailView);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the WonLostDetailViews EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWonLostDetailViews(WonLostDetailView wonLostDetailView)
        {
            base.AddObject("WonLostDetailViews", wonLostDetailView);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SoftballModel", Name="Game")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Game : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Game object.
        /// </summary>
        /// <param name="gameID">Initial value of the GameID property.</param>
        /// <param name="atHomeFirst">Initial value of the AtHomeFirst property.</param>
        public static Game CreateGame(global::System.Int32 gameID, global::System.Boolean atHomeFirst)
        {
            Game game = new Game();
            game.GameID = gameID;
            game.AtHomeFirst = atHomeFirst;
            return game;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GameID
        {
            get
            {
                return _GameID;
            }
            set
            {
                if (_GameID != value)
                {
                    OnGameIDChanging(value);
                    ReportPropertyChanging("GameID");
                    _GameID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GameID");
                    OnGameIDChanged();
                }
            }
        }
        private global::System.Int32 _GameID;
        partial void OnGameIDChanging(global::System.Int32 value);
        partial void OnGameIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GameLocation
        {
            get
            {
                return _GameLocation;
            }
            set
            {
                OnGameLocationChanging(value);
                ReportPropertyChanging("GameLocation");
                _GameLocation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GameLocation");
                OnGameLocationChanged();
            }
        }
        private global::System.String _GameLocation;
        partial void OnGameLocationChanging(global::System.String value);
        partial void OnGameLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> GameDate
        {
            get
            {
                return _GameDate;
            }
            set
            {
                OnGameDateChanging(value);
                ReportPropertyChanging("GameDate");
                _GameDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GameDate");
                OnGameDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _GameDate;
        partial void OnGameDateChanging(Nullable<global::System.DateTime> value);
        partial void OnGameDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean AtHomeFirst
        {
            get
            {
                return _AtHomeFirst;
            }
            set
            {
                OnAtHomeFirstChanging(value);
                ReportPropertyChanging("AtHomeFirst");
                _AtHomeFirst = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AtHomeFirst");
                OnAtHomeFirstChanged();
            }
        }
        private global::System.Boolean _AtHomeFirst;
        partial void OnAtHomeFirstChanging(global::System.Boolean value);
        partial void OnAtHomeFirstChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GameStatus
        {
            get
            {
                return _GameStatus;
            }
            set
            {
                OnGameStatusChanging(value);
                ReportPropertyChanging("GameStatus");
                _GameStatus = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GameStatus");
                OnGameStatusChanged();
            }
        }
        private global::System.String _GameStatus;
        partial void OnGameStatusChanging(global::System.String value);
        partial void OnGameStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Game1Result
        {
            get
            {
                return _Game1Result;
            }
            set
            {
                OnGame1ResultChanging(value);
                ReportPropertyChanging("Game1Result");
                _Game1Result = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Game1Result");
                OnGame1ResultChanged();
            }
        }
        private global::System.String _Game1Result;
        partial void OnGame1ResultChanging(global::System.String value);
        partial void OnGame1ResultChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Game2Result
        {
            get
            {
                return _Game2Result;
            }
            set
            {
                OnGame2ResultChanging(value);
                ReportPropertyChanging("Game2Result");
                _Game2Result = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Game2Result");
                OnGame2ResultChanged();
            }
        }
        private global::System.String _Game2Result;
        partial void OnGame2ResultChanging(global::System.String value);
        partial void OnGame2ResultChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Opponent
        {
            get
            {
                return _Opponent;
            }
            set
            {
                OnOpponentChanging(value);
                ReportPropertyChanging("Opponent");
                _Opponent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Opponent");
                OnOpponentChanged();
            }
        }
        private global::System.String _Opponent;
        partial void OnOpponentChanging(global::System.String value);
        partial void OnOpponentChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SoftballModel", Name="Player")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Player : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Player object.
        /// </summary>
        /// <param name="playerID">Initial value of the PlayerID property.</param>
        /// <param name="isEmailEnabled">Initial value of the IsEmailEnabled property.</param>
        /// <param name="isTextEnabled">Initial value of the IsTextEnabled property.</param>
        /// <param name="isActive">Initial value of the IsActive property.</param>
        public static Player CreatePlayer(global::System.Int32 playerID, global::System.Boolean isEmailEnabled, global::System.Boolean isTextEnabled, global::System.Boolean isActive)
        {
            Player player = new Player();
            player.PlayerID = playerID;
            player.IsEmailEnabled = isEmailEnabled;
            player.IsTextEnabled = isTextEnabled;
            player.IsActive = isActive;
            return player;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PlayerID
        {
            get
            {
                return _PlayerID;
            }
            set
            {
                if (_PlayerID != value)
                {
                    OnPlayerIDChanging(value);
                    ReportPropertyChanging("PlayerID");
                    _PlayerID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PlayerID");
                    OnPlayerIDChanged();
                }
            }
        }
        private global::System.Int32 _PlayerID;
        partial void OnPlayerIDChanging(global::System.Int32 value);
        partial void OnPlayerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhoneNumber
        {
            get
            {
                return _PhoneNumber;
            }
            set
            {
                OnPhoneNumberChanging(value);
                ReportPropertyChanging("PhoneNumber");
                _PhoneNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PhoneNumber");
                OnPhoneNumberChanged();
            }
        }
        private global::System.String _PhoneNumber;
        partial void OnPhoneNumberChanging(global::System.String value);
        partial void OnPhoneNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CellNumber
        {
            get
            {
                return _CellNumber;
            }
            set
            {
                OnCellNumberChanging(value);
                ReportPropertyChanging("CellNumber");
                _CellNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CellNumber");
                OnCellNumberChanged();
            }
        }
        private global::System.String _CellNumber;
        partial void OnCellNumberChanging(global::System.String value);
        partial void OnCellNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TextEmail
        {
            get
            {
                return _TextEmail;
            }
            set
            {
                OnTextEmailChanging(value);
                ReportPropertyChanging("TextEmail");
                _TextEmail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TextEmail");
                OnTextEmailChanged();
            }
        }
        private global::System.String _TextEmail;
        partial void OnTextEmailChanging(global::System.String value);
        partial void OnTextEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsEmailEnabled
        {
            get
            {
                return _IsEmailEnabled;
            }
            set
            {
                OnIsEmailEnabledChanging(value);
                ReportPropertyChanging("IsEmailEnabled");
                _IsEmailEnabled = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsEmailEnabled");
                OnIsEmailEnabledChanged();
            }
        }
        private global::System.Boolean _IsEmailEnabled;
        partial void OnIsEmailEnabledChanging(global::System.Boolean value);
        partial void OnIsEmailEnabledChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsTextEnabled
        {
            get
            {
                return _IsTextEnabled;
            }
            set
            {
                OnIsTextEnabledChanging(value);
                ReportPropertyChanging("IsTextEnabled");
                _IsTextEnabled = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsTextEnabled");
                OnIsTextEnabledChanged();
            }
        }
        private global::System.Boolean _IsTextEnabled;
        partial void OnIsTextEnabledChanging(global::System.Boolean value);
        partial void OnIsTextEnabledChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private global::System.Boolean _IsActive;
        partial void OnIsActiveChanging(global::System.Boolean value);
        partial void OnIsActiveChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SoftballModel", Name="Schedule")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Schedule : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Schedule object.
        /// </summary>
        /// <param name="scheduleID">Initial value of the ScheduleID property.</param>
        public static Schedule CreateSchedule(global::System.Int32 scheduleID)
        {
            Schedule schedule = new Schedule();
            schedule.ScheduleID = scheduleID;
            return schedule;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ScheduleID
        {
            get
            {
                return _ScheduleID;
            }
            set
            {
                if (_ScheduleID != value)
                {
                    OnScheduleIDChanging(value);
                    ReportPropertyChanging("ScheduleID");
                    _ScheduleID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ScheduleID");
                    OnScheduleIDChanged();
                }
            }
        }
        private global::System.Int32 _ScheduleID;
        partial void OnScheduleIDChanging(global::System.Int32 value);
        partial void OnScheduleIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ScheduleDate
        {
            get
            {
                return _ScheduleDate;
            }
            set
            {
                OnScheduleDateChanging(value);
                ReportPropertyChanging("ScheduleDate");
                _ScheduleDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ScheduleDate");
                OnScheduleDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ScheduleDate;
        partial void OnScheduleDateChanging(Nullable<global::System.DateTime> value);
        partial void OnScheduleDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> HomeTeam
        {
            get
            {
                return _HomeTeam;
            }
            set
            {
                OnHomeTeamChanging(value);
                ReportPropertyChanging("HomeTeam");
                _HomeTeam = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HomeTeam");
                OnHomeTeamChanged();
            }
        }
        private Nullable<global::System.Int32> _HomeTeam;
        partial void OnHomeTeamChanging(Nullable<global::System.Int32> value);
        partial void OnHomeTeamChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AwayTeam
        {
            get
            {
                return _AwayTeam;
            }
            set
            {
                OnAwayTeamChanging(value);
                ReportPropertyChanging("AwayTeam");
                _AwayTeam = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AwayTeam");
                OnAwayTeamChanged();
            }
        }
        private Nullable<global::System.Int32> _AwayTeam;
        partial void OnAwayTeamChanging(Nullable<global::System.Int32> value);
        partial void OnAwayTeamChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SoftballModel", "FK_Schedule_Team", "Team")]
        public Team Team
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Team>("SoftballModel.FK_Schedule_Team", "Team").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Team>("SoftballModel.FK_Schedule_Team", "Team").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Team> TeamReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Team>("SoftballModel.FK_Schedule_Team", "Team");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Team>("SoftballModel.FK_Schedule_Team", "Team", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SoftballModel", "FK_Schedule_Team1", "Team")]
        public Team Team1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Team>("SoftballModel.FK_Schedule_Team1", "Team").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Team>("SoftballModel.FK_Schedule_Team1", "Team").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Team> Team1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Team>("SoftballModel.FK_Schedule_Team1", "Team");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Team>("SoftballModel.FK_Schedule_Team1", "Team", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SoftballModel", Name="ScheduleDetailView")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ScheduleDetailView : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ScheduleDetailView object.
        /// </summary>
        /// <param name="scheduleID">Initial value of the ScheduleID property.</param>
        public static ScheduleDetailView CreateScheduleDetailView(global::System.Int32 scheduleID)
        {
            ScheduleDetailView scheduleDetailView = new ScheduleDetailView();
            scheduleDetailView.ScheduleID = scheduleID;
            return scheduleDetailView;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ScheduleID
        {
            get
            {
                return _ScheduleID;
            }
            set
            {
                if (_ScheduleID != value)
                {
                    OnScheduleIDChanging(value);
                    ReportPropertyChanging("ScheduleID");
                    _ScheduleID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ScheduleID");
                    OnScheduleIDChanged();
                }
            }
        }
        private global::System.Int32 _ScheduleID;
        partial void OnScheduleIDChanging(global::System.Int32 value);
        partial void OnScheduleIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ScheduleDate
        {
            get
            {
                return _ScheduleDate;
            }
            set
            {
                OnScheduleDateChanging(value);
                ReportPropertyChanging("ScheduleDate");
                _ScheduleDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ScheduleDate");
                OnScheduleDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ScheduleDate;
        partial void OnScheduleDateChanging(Nullable<global::System.DateTime> value);
        partial void OnScheduleDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HomeTeam
        {
            get
            {
                return _HomeTeam;
            }
            set
            {
                OnHomeTeamChanging(value);
                ReportPropertyChanging("HomeTeam");
                _HomeTeam = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HomeTeam");
                OnHomeTeamChanged();
            }
        }
        private global::System.String _HomeTeam;
        partial void OnHomeTeamChanging(global::System.String value);
        partial void OnHomeTeamChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HomeManager
        {
            get
            {
                return _HomeManager;
            }
            set
            {
                OnHomeManagerChanging(value);
                ReportPropertyChanging("HomeManager");
                _HomeManager = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HomeManager");
                OnHomeManagerChanged();
            }
        }
        private global::System.String _HomeManager;
        partial void OnHomeManagerChanging(global::System.String value);
        partial void OnHomeManagerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AwayTeam
        {
            get
            {
                return _AwayTeam;
            }
            set
            {
                OnAwayTeamChanging(value);
                ReportPropertyChanging("AwayTeam");
                _AwayTeam = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AwayTeam");
                OnAwayTeamChanged();
            }
        }
        private global::System.String _AwayTeam;
        partial void OnAwayTeamChanging(global::System.String value);
        partial void OnAwayTeamChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AwayManager
        {
            get
            {
                return _AwayManager;
            }
            set
            {
                OnAwayManagerChanging(value);
                ReportPropertyChanging("AwayManager");
                _AwayManager = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AwayManager");
                OnAwayManagerChanged();
            }
        }
        private global::System.String _AwayManager;
        partial void OnAwayManagerChanging(global::System.String value);
        partial void OnAwayManagerChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SoftballModel", Name="Team")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Team : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Team object.
        /// </summary>
        /// <param name="teamID">Initial value of the TeamID property.</param>
        public static Team CreateTeam(global::System.Int32 teamID)
        {
            Team team = new Team();
            team.TeamID = teamID;
            return team;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TeamID
        {
            get
            {
                return _TeamID;
            }
            set
            {
                if (_TeamID != value)
                {
                    OnTeamIDChanging(value);
                    ReportPropertyChanging("TeamID");
                    _TeamID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TeamID");
                    OnTeamIDChanged();
                }
            }
        }
        private global::System.Int32 _TeamID;
        partial void OnTeamIDChanging(global::System.Int32 value);
        partial void OnTeamIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TeamName
        {
            get
            {
                return _TeamName;
            }
            set
            {
                OnTeamNameChanging(value);
                ReportPropertyChanging("TeamName");
                _TeamName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TeamName");
                OnTeamNameChanged();
            }
        }
        private global::System.String _TeamName;
        partial void OnTeamNameChanging(global::System.String value);
        partial void OnTeamNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Manager
        {
            get
            {
                return _Manager;
            }
            set
            {
                OnManagerChanging(value);
                ReportPropertyChanging("Manager");
                _Manager = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Manager");
                OnManagerChanged();
            }
        }
        private global::System.String _Manager;
        partial void OnManagerChanging(global::System.String value);
        partial void OnManagerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HomeCell
        {
            get
            {
                return _HomeCell;
            }
            set
            {
                OnHomeCellChanging(value);
                ReportPropertyChanging("HomeCell");
                _HomeCell = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HomeCell");
                OnHomeCellChanged();
            }
        }
        private global::System.String _HomeCell;
        partial void OnHomeCellChanging(global::System.String value);
        partial void OnHomeCellChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WorkCell
        {
            get
            {
                return _WorkCell;
            }
            set
            {
                OnWorkCellChanging(value);
                ReportPropertyChanging("WorkCell");
                _WorkCell = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("WorkCell");
                OnWorkCellChanged();
            }
        }
        private global::System.String _WorkCell;
        partial void OnWorkCellChanging(global::System.String value);
        partial void OnWorkCellChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SoftballModel", "FK_Schedule_Team", "Schedule")]
        public EntityCollection<Schedule> Schedules
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Schedule>("SoftballModel.FK_Schedule_Team", "Schedule");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Schedule>("SoftballModel.FK_Schedule_Team", "Schedule", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SoftballModel", "FK_Schedule_Team1", "Schedule")]
        public EntityCollection<Schedule> Schedules1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Schedule>("SoftballModel.FK_Schedule_Team1", "Schedule");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Schedule>("SoftballModel.FK_Schedule_Team1", "Schedule", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SoftballModel", Name="WonLostDetailView")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WonLostDetailView : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new WonLostDetailView object.
        /// </summary>
        /// <param name="loss1">Initial value of the Loss1 property.</param>
        /// <param name="win1">Initial value of the Win1 property.</param>
        /// <param name="loss2">Initial value of the Loss2 property.</param>
        /// <param name="win2">Initial value of the Win2 property.</param>
        public static WonLostDetailView CreateWonLostDetailView(global::System.Int32 loss1, global::System.Int32 win1, global::System.Int32 loss2, global::System.Int32 win2)
        {
            WonLostDetailView wonLostDetailView = new WonLostDetailView();
            wonLostDetailView.Loss1 = loss1;
            wonLostDetailView.Win1 = win1;
            wonLostDetailView.Loss2 = loss2;
            wonLostDetailView.Win2 = win2;
            return wonLostDetailView;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Loss1
        {
            get
            {
                return _Loss1;
            }
            set
            {
                if (_Loss1 != value)
                {
                    OnLoss1Changing(value);
                    ReportPropertyChanging("Loss1");
                    _Loss1 = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Loss1");
                    OnLoss1Changed();
                }
            }
        }
        private global::System.Int32 _Loss1;
        partial void OnLoss1Changing(global::System.Int32 value);
        partial void OnLoss1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Win1
        {
            get
            {
                return _Win1;
            }
            set
            {
                if (_Win1 != value)
                {
                    OnWin1Changing(value);
                    ReportPropertyChanging("Win1");
                    _Win1 = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Win1");
                    OnWin1Changed();
                }
            }
        }
        private global::System.Int32 _Win1;
        partial void OnWin1Changing(global::System.Int32 value);
        partial void OnWin1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Loss2
        {
            get
            {
                return _Loss2;
            }
            set
            {
                if (_Loss2 != value)
                {
                    OnLoss2Changing(value);
                    ReportPropertyChanging("Loss2");
                    _Loss2 = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Loss2");
                    OnLoss2Changed();
                }
            }
        }
        private global::System.Int32 _Loss2;
        partial void OnLoss2Changing(global::System.Int32 value);
        partial void OnLoss2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Win2
        {
            get
            {
                return _Win2;
            }
            set
            {
                if (_Win2 != value)
                {
                    OnWin2Changing(value);
                    ReportPropertyChanging("Win2");
                    _Win2 = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Win2");
                    OnWin2Changed();
                }
            }
        }
        private global::System.Int32 _Win2;
        partial void OnWin2Changing(global::System.Int32 value);
        partial void OnWin2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Year
        {
            get
            {
                return _Year;
            }
            set
            {
                OnYearChanging(value);
                ReportPropertyChanging("Year");
                _Year = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Year");
                OnYearChanged();
            }
        }
        private Nullable<global::System.Int32> _Year;
        partial void OnYearChanging(Nullable<global::System.Int32> value);
        partial void OnYearChanged();

        #endregion

    
    }

    #endregion

    
}
