//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Softball.Mvc4
{
    using System;
    using System.Collections.Generic;
    
    public partial class WonLostDetailView
    {
        public int Loss1 { get; set; }
        public int Win1 { get; set; }
        public int Loss2 { get; set; }
        public int Win2 { get; set; }
        public Nullable<int> Year { get; set; }
    }
}
